{% set version = "1.3.4.1" %}

package:
  name: wrf-python
  version: {{ version }}

source:
#  for develop
  git_url: https://github.com/NCAR/wrf-python
  git_branch: develop
#  for release
#  fn: wrf-python-{{ version }}.tar.gz
#  url: https://github.com/NCAR/wrf-python/archive/{{ version }}.tar.gz
#  sha256: 9ca11366ed9a0d5e83e576ac80ce36be4748ba8a06752dac077277acec5e46d9
  
build:
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:
    - setuptools
    - python
    - numpy 1.11.*  # [unix]
    - numpy 1.14.*  # [win]
    - wrapt
    - m2w64-toolchain  # [win]
    - gcc # [unix] 
  run:
    - setuptools
    - numpy >=1.11  # [unix]
    - numpy >=1.14  # [win] 
    - python
    - wrapt 
    - m2w64-gcc-libs  # [win]
    - libgfortran  # [unix]
    - libgcc  # [unix]
    - xarray

test:
  requires:
    - setuptools
    - netcdf4
    - xarray
  source_files:
    - test/ci_tests
  imports:
    - wrf
  commands:
    - cd test/ci_tests && python utests.py 

about:
  home: https://github.com/NCAR/wrf-python
  license: "UCAR"
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE' 
  summary: "Diagnostic and interpolation routines for WRF-ARW data."

extra:
  recipe-maintainers:
    - michaelavs
    - erogluorhan
    
